# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.19.6-alpine
COPY ./distribution /usr/share/nginx/html
RUN ls /usr/share/nginx/html
# Copy the default nginx.conf
COPY ./dockerfile/nginx-custom.conf /etc/nginx/conf.d/default.conf
RUN ls /etc/nginx/conf.d
# expose port
EXPOSE 80
# run nginx
CMD ["nginx", "-g", "daemon off;"]