# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM node:14 as build-stage

# # install chrome for protractor tests
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

WORKDIR /app
COPY package*.json /app/
RUN npm install
# Install specific angular version, if the app updates this must be updated as well
RUN npm install -g @angular/cli@12.0.5
COPY ./ /app/
# Run unit tests
RUN ng test --code-coverage --browsers ChromeHeadlessNoSandbox --watch=false; exit 0
# Configuration can be read from environmental variables setup on the CI/CD server
ARG configuration=production
# Build the angular application
RUN ng build --output-path=./dist/out --configuration $configuration