# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM tiangolo/node-frontend:10 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
# Install specific angular version, if the app updates this must be updated as well
RUN npm install -g @angular/cli@11.0.5
COPY ./ /app/
# Run unit tests
RUN ng test --browsers ChromeHeadlessNoSandbox --watch=false