export enum Nationality {
    'British',
    'Scottish',
    'Irish',
    'Welsh'  ,
    'Danish' ,
    'Finnish' ,
    'Norwegian' ,
    'Swedish' ,
    'Swiss'  ,
    'Estonian'  ,
    'Latvian'  ,
    'Lithuanian'  ,
    'Austrian'  ,
    'Belgian' ,
    'French'  ,
    'German'  ,
    'Italian'  ,
    'Dutch'  ,
    'American'  ,
    'Canadian'  ,
    'Mexican'  ,
    'Ukrainian'  ,
    'Russian'  ,
    'Belarusian'  ,
    'Polish'  ,
    'Czech'  ,
    'Slovak / Slovakian'  ,
    'Hungarian'  ,
    'Romanian'  ,
    'Bulgarian'  ,
    'Greek'  ,
    'Spanish'  ,
    'Brazilian'  ,
    'Portuguese'  ,
    'Australian'  ,
    'New Zealander'  ,
    'Georgian'  ,
    'Israeli'  ,
    'Egyptian'  ,
    'Turkish'  ,
    'Chinese'  ,
    'Korean'  ,
    'Japanese'  ,
    'Indian'  ,
    'South African'
}
